export type Question = {
  id: number;
  topic: string;
  question: string;
  options: [string, string, string, string];
  answer: number;
  explanation: string;
};

export const QUESTION_BANK: Question[] = [
  {
    id: 1,
    topic: "Nền tảng AI",
    question: "AI là viết tắt của cụm từ nào?",
    options: ["Automated Internet", "Artificial Intelligence", "Advanced Input", "Applied Information"],
    answer: 1,
    explanation: "AI là Artificial Intelligence — Trí tuệ nhân tạo.",
  },
  {
    id: 2,
    topic: "Nền tảng AI",
    question: "Machine Learning là một nhánh của lĩnh vực nào?",
    options: ["Trí tuệ nhân tạo", "Thiết kế đồ họa", "Mạng máy tính", "Hệ điều hành"],
    answer: 0,
    explanation: "Machine Learning là một nhánh của AI, cho phép máy học từ dữ liệu.",
  },
  {
    id: 3,
    topic: "Nền tảng AI",
    question: "Mục tiêu chính của Machine Learning là gì?",
    options: ["Tăng dung lượng ổ cứng", "Học quy luật từ dữ liệu", "Thay màn hình máy tính", "Nén mọi loại tệp"],
    answer: 1,
    explanation: "Mô hình ML học các mẫu và quy luật từ dữ liệu để dự đoán hoặc ra quyết định.",
  },
  {
    id: 4,
    topic: "Nền tảng AI",
    question: "Ví dụ nào là một bài toán Machine Learning?",
    options: ["Dự đoán giá nhà", "Đổi tên một thư mục", "Bật máy tính", "Cắm cáp mạng"],
    answer: 0,
    explanation: "Dự đoán giá nhà dùng dữ liệu quá khứ để học và dự đoán giá mới.",
  },
  {
    id: 5,
    topic: "Nền tảng AI",
    question: "Hệ thống lọc thư rác thường giải quyết dạng bài toán nào?",
    options: ["Phân loại", "Sắp xếp thủ công", "Nén dữ liệu", "Kết xuất hình ảnh"],
    answer: 0,
    explanation: "Email thường được phân loại thành thư rác hoặc không phải thư rác.",
  },
  {
    id: 6,
    topic: "Nền tảng AI",
    question: "Dự đoán nhiệt độ ngày mai là ví dụ gần nhất của bài toán nào?",
    options: ["Phân loại nhị phân", "Hồi quy", "Phân cụm", "Giảm chiều"],
    answer: 1,
    explanation: "Nhiệt độ là một giá trị số liên tục nên phù hợp với bài toán hồi quy.",
  },
  {
    id: 7,
    topic: "Nền tảng AI",
    question: "Nhận diện ảnh mèo và chó là bài toán gì?",
    options: ["Hồi quy", "Phân loại", "Nén ảnh", "Tạo cơ sở dữ liệu"],
    answer: 1,
    explanation: "Mô hình chọn một trong các nhãn rời rạc: mèo hoặc chó.",
  },
  {
    id: 8,
    topic: "Nền tảng AI",
    question: "Một mô hình đã học xong được dùng trên dữ liệu mới để làm gì?",
    options: ["Dự đoán", "Xóa dữ liệu", "Đổi tên cột", "Tắt máy"],
    answer: 0,
    explanation: "Sau khi huấn luyện, mô hình thực hiện suy luận để tạo dự đoán trên dữ liệu mới.",
  },
  {
    id: 9,
    topic: "Nền tảng AI",
    question: "Thuật ngữ nào chỉ quá trình mô hình học từ dữ liệu?",
    options: ["Training", "Printing", "Browsing", "Formatting"],
    answer: 0,
    explanation: "Training là quá trình điều chỉnh mô hình dựa trên dữ liệu huấn luyện.",
  },
  {
    id: 10,
    topic: "Nền tảng AI",
    question: "Đầu ra do mô hình tạo ra cho một mẫu mới thường được gọi là gì?",
    options: ["Prediction", "Folder", "Browser", "Compiler"],
    answer: 0,
    explanation: "Prediction là giá trị hoặc nhãn mà mô hình dự đoán.",
  },
  {
    id: 11,
    topic: "Dữ liệu",
    question: "Trong bảng dữ liệu, mỗi hàng thường biểu diễn điều gì?",
    options: ["Một quan sát", "Một thuật toán", "Một thư viện", "Một biểu đồ"],
    answer: 0,
    explanation: "Mỗi hàng thường là một mẫu hoặc quan sát trong tập dữ liệu.",
  },
  {
    id: 12,
    topic: "Dữ liệu",
    question: "Trong bảng dữ liệu, một cột đầu vào thường được gọi là gì?",
    options: ["Feature", "Epoch", "Cluster", "Loss"],
    answer: 0,
    explanation: "Feature là thuộc tính đầu vào được dùng để mô tả một quan sát.",
  },
  {
    id: 13,
    topic: "Dữ liệu",
    question: "Cột cần dự đoán trong học có giám sát được gọi là gì?",
    options: ["Target", "Index", "Header", "Cache"],
    answer: 0,
    explanation: "Target hoặc label là biến mục tiêu mà mô hình cần dự đoán.",
  },
  {
    id: 14,
    topic: "Dữ liệu",
    question: "Trong dữ liệu chiến dịch marketing, cột “Responded” cần dự đoán nên là gì?",
    options: ["Feature ngẫu nhiên", "Target", "Tên tệp", "Siêu tham số"],
    answer: 1,
    explanation: "“Responded” là kết quả cần dự đoán nên đóng vai trò target.",
  },
  {
    id: 15,
    topic: "Dữ liệu",
    question: "Giá trị bị thiếu trong Pandas thường được biểu diễn bằng gì?",
    options: ["NaN", "HTML", "GPU", "URL"],
    answer: 0,
    explanation: "NaN là ký hiệu thường gặp cho dữ liệu số bị thiếu.",
  },
  {
    id: 16,
    topic: "Dữ liệu",
    question: "Thao tác nào có thể xử lý dữ liệu bị thiếu?",
    options: ["Điền giá trị phù hợp", "Tăng độ sáng màn hình", "Đổi trình duyệt", "Tắt bàn phím"],
    answer: 0,
    explanation: "Có thể điền trung bình, trung vị, mode hoặc một giá trị hợp lý tùy dữ liệu.",
  },
  {
    id: 17,
    topic: "Dữ liệu",
    question: "Chuẩn hóa đặc trưng giúp điều gì?",
    options: ["Đưa các đặc trưng về thang đo tương đồng", "Tạo thêm màn hình", "Xóa hệ điều hành", "Đổi tên mô hình"],
    answer: 0,
    explanation: "Scaling hạn chế việc đặc trưng có thang đo lớn lấn át đặc trưng khác.",
  },
  {
    id: 18,
    topic: "Dữ liệu",
    question: "StandardScaler thường biến đổi dữ liệu để có đặc điểm nào?",
    options: ["Trung bình gần 0 và độ lệch chuẩn gần 1", "Mọi giá trị bằng 1", "Mọi giá trị là số nguyên", "Không còn cột"],
    answer: 0,
    explanation: "StandardScaler chuẩn hóa theo z-score: trừ trung bình và chia độ lệch chuẩn.",
  },
  {
    id: 19,
    topic: "Dữ liệu",
    question: "One-hot encoding thường dùng cho loại dữ liệu nào?",
    options: ["Dữ liệu phân loại", "Ảnh đã in", "Mật khẩu", "Địa chỉ IP"],
    answer: 0,
    explanation: "One-hot encoding chuyển các nhóm phân loại thành các cột nhị phân.",
  },
  {
    id: 20,
    topic: "Dữ liệu",
    question: "Vì sao nên xáo trộn dữ liệu trước khi chia tập?",
    options: ["Giảm ảnh hưởng của thứ tự dữ liệu", "Làm tệp lớn hơn", "Tăng số cột", "Đổi kiểu bàn phím"],
    answer: 0,
    explanation: "Xáo trộn giúp các tập con đại diện tốt hơn cho phân phối chung.",
  },
  {
    id: 21,
    topic: "Dữ liệu",
    question: "Tập training dùng để làm gì?",
    options: ["Huấn luyện mô hình", "Chỉ để trang trí", "Lưu mật khẩu", "Cài trình duyệt"],
    answer: 0,
    explanation: "Mô hình học tham số từ tập training.",
  },
  {
    id: 22,
    topic: "Dữ liệu",
    question: "Tập test nên được dùng khi nào?",
    options: ["Đánh giá cuối cùng", "Huấn luyện lặp đi lặp lại", "Chọn màu giao diện", "Tạo tên cột"],
    answer: 0,
    explanation: "Tập test được giữ riêng để ước lượng khả năng tổng quát hóa sau cùng.",
  },
  {
    id: 23,
    topic: "Dữ liệu",
    question: "Data leakage xảy ra khi nào?",
    options: ["Thông tin không nên có lọt vào quá trình huấn luyện", "Máy tính hết pin", "Mất kết nối Wi-Fi", "Tệp được nén"],
    answer: 0,
    explanation: "Leakage khiến mô hình biết trước thông tin và cho kết quả đánh giá quá lạc quan.",
  },
  {
    id: 24,
    topic: "Dữ liệu",
    question: "Ngoại lệ (outlier) là gì?",
    options: ["Giá trị khác biệt mạnh so với phần lớn dữ liệu", "Tên của mô hình", "Một kiểu biểu đồ", "Một tệp Python"],
    answer: 0,
    explanation: "Outlier là quan sát bất thường, nằm xa xu hướng chung.",
  },
  {
    id: 25,
    topic: "Dữ liệu",
    question: "Thư viện Python nào phổ biến để làm việc với bảng dữ liệu?",
    options: ["Pandas", "Turtle", "Tkinter", "Socket"],
    answer: 0,
    explanation: "Pandas cung cấp DataFrame và nhiều công cụ xử lý dữ liệu dạng bảng.",
  },
  {
    id: 26,
    topic: "Học có giám sát",
    question: "Học có giám sát cần dữ liệu có gì?",
    options: ["Nhãn", "Chỉ hình nền", "Chỉ tên tệp", "Không có quan sát"],
    answer: 0,
    explanation: "Supervised learning học ánh xạ từ đầu vào đến nhãn đã biết.",
  },
  {
    id: 27,
    topic: "Học có giám sát",
    question: "Phân loại nhị phân có bao nhiêu lớp?",
    options: ["2", "3", "10", "Không có lớp"],
    answer: 0,
    explanation: "Binary classification phân biệt giữa hai lớp.",
  },
  {
    id: 28,
    topic: "Học có giám sát",
    question: "Bài toán dự đoán đậu hoặc trượt là loại nào?",
    options: ["Phân loại nhị phân", "Hồi quy", "Phân cụm", "Giảm chiều"],
    answer: 0,
    explanation: "Đậu và trượt là hai nhãn rời rạc.",
  },
  {
    id: 29,
    topic: "Học có giám sát",
    question: "Bài toán dự đoán lương theo số năm kinh nghiệm thuộc loại nào?",
    options: ["Hồi quy", "Phân loại", "Phân cụm", "Luật kết hợp"],
    answer: 0,
    explanation: "Lương là đại lượng số liên tục nên dùng hồi quy.",
  },
  {
    id: 30,
    topic: "Học có giám sát",
    question: "Linear Regression tìm mối quan hệ có dạng cơ bản nào?",
    options: ["Tuyến tính", "Chỉ dạng cây", "Chỉ dạng vòng tròn", "Không dùng dữ liệu"],
    answer: 0,
    explanation: "Hồi quy tuyến tính mô hình hóa target bằng tổ hợp tuyến tính của các feature.",
  },
  {
    id: 31,
    topic: "Học có giám sát",
    question: "Logistic Regression thường được dùng cho bài toán nào?",
    options: ["Phân loại", "Nén ảnh", "Mã hóa tệp", "Sắp xếp thư mục"],
    answer: 0,
    explanation: "Dù có tên Regression, Logistic Regression thường dùng để phân loại.",
  },
  {
    id: 32,
    topic: "Học có giám sát",
    question: "Đầu ra của hàm sigmoid nằm trong khoảng nào?",
    options: ["Từ 0 đến 1", "Từ 10 đến 20", "Từ -100 đến 100", "Luôn lớn hơn 1000"],
    answer: 0,
    explanation: "Sigmoid ánh xạ mọi số thực vào khoảng từ 0 đến 1.",
  },
  {
    id: 33,
    topic: "Học có giám sát",
    question: "Trong phân loại, class label là gì?",
    options: ["Nhãn lớp cần dự đoán", "Kích thước màn hình", "Tên ổ đĩa", "Số dòng mã"],
    answer: 0,
    explanation: "Class label biểu diễn nhóm mà một quan sát thuộc về.",
  },
  {
    id: 34,
    topic: "Học có giám sát",
    question: "Ranh giới phân chia các lớp được gọi là gì?",
    options: ["Decision boundary", "File boundary", "Screen border", "Data folder"],
    answer: 0,
    explanation: "Decision boundary là đường hoặc bề mặt phân tách vùng dự đoán của các lớp.",
  },
  {
    id: 35,
    topic: "Học có giám sát",
    question: "Mô hình tổng quát hóa tốt khi nào?",
    options: ["Hoạt động tốt trên dữ liệu chưa thấy", "Chỉ nhớ dữ liệu train", "Có tên thật dài", "Dùng nhiều màu"],
    answer: 0,
    explanation: "Khả năng tổng quát hóa thể hiện qua hiệu quả trên dữ liệu mới.",
  },
  {
    id: 36,
    topic: "Đánh giá mô hình",
    question: "Accuracy được tính như thế nào?",
    options: ["Số dự đoán đúng chia tổng số dự đoán", "Số cột chia số hàng", "TP chia FP", "Sai số lớn nhất"],
    answer: 0,
    explanation: "Accuracy là tỷ lệ toàn bộ dự đoán đúng.",
  },
  {
    id: 37,
    topic: "Đánh giá mô hình",
    question: "Confusion matrix dùng chủ yếu cho bài toán nào?",
    options: ["Phân loại", "Nén dữ liệu", "Thiết kế web", "Tạo ảnh"],
    answer: 0,
    explanation: "Confusion matrix tổng hợp số dự đoán đúng/sai theo từng lớp.",
  },
  {
    id: 38,
    topic: "Đánh giá mô hình",
    question: "TP trong confusion matrix là viết tắt của gì?",
    options: ["True Positive", "Total Prediction", "Training Process", "Target Point"],
    answer: 0,
    explanation: "True Positive là mẫu dương tính được dự đoán đúng là dương tính.",
  },
  {
    id: 39,
    topic: "Đánh giá mô hình",
    question: "False Positive có nghĩa là gì?",
    options: ["Dự đoán dương nhưng thực tế âm", "Dự đoán âm và thực tế âm", "Dự đoán dương và thực tế dương", "Không có dự đoán"],
    answer: 0,
    explanation: "False Positive là báo động nhầm: dự đoán dương tính nhưng thực tế âm tính.",
  },
  {
    id: 40,
    topic: "Đánh giá mô hình",
    question: "Recall cao đặc biệt quan trọng khi nào?",
    options: ["Cần hạn chế bỏ sót ca dương tính", "Cần đổi màu biểu đồ", "Cần giảm số cột bằng 0", "Cần in tệp"],
    answer: 0,
    explanation: "Recall đo khả năng tìm ra các mẫu dương tính thực sự.",
  },
  {
    id: 41,
    topic: "Đánh giá mô hình",
    question: "Precision trả lời câu hỏi nào?",
    options: ["Trong các mẫu dự đoán dương, bao nhiêu mẫu đúng?", "Có bao nhiêu cột?", "Dữ liệu có bao nhiêu byte?", "Mô hình chạy bao nhiêu giây?"],
    answer: 0,
    explanation: "Precision = TP / (TP + FP).",
  },
  {
    id: 42,
    topic: "Đánh giá mô hình",
    question: "F1-score kết hợp hai chỉ số nào?",
    options: ["Precision và Recall", "MSE và MAE", "RAM và CPU", "Train và Test"],
    answer: 0,
    explanation: "F1 là trung bình điều hòa của Precision và Recall.",
  },
  {
    id: 43,
    topic: "Đánh giá mô hình",
    question: "MAE là thước đo thường dùng cho loại bài toán nào?",
    options: ["Hồi quy", "Phân loại văn bản", "Phân cụm duy nhất", "Nén ảnh"],
    answer: 0,
    explanation: "Mean Absolute Error đo trung bình độ lớn sai số dự đoán trong hồi quy.",
  },
  {
    id: 44,
    topic: "Đánh giá mô hình",
    question: "MSE xử lý sai số lớn như thế nào?",
    options: ["Phạt mạnh hơn do bình phương sai số", "Bỏ qua hoàn toàn", "Đổi thành nhãn", "Luôn đặt bằng 0"],
    answer: 0,
    explanation: "Vì sai số được bình phương, các sai lệch lớn có ảnh hưởng mạnh hơn.",
  },
  {
    id: 45,
    topic: "Đánh giá mô hình",
    question: "Giá trị loss thấp hơn thường cho biết điều gì?",
    options: ["Mô hình khớp mục tiêu tốt hơn", "Tệp lớn hơn", "Có nhiều cột hơn", "Máy tính nóng hơn"],
    answer: 0,
    explanation: "Loss đo mức sai lệch; trong cùng điều kiện, loss thấp thường tốt hơn.",
  },
  {
    id: 46,
    topic: "Đánh giá mô hình",
    question: "Overfitting là hiện tượng nào?",
    options: ["Tốt trên train nhưng kém trên dữ liệu mới", "Kém cả train và test vì quá đơn giản", "Không có dữ liệu", "Không có target"],
    answer: 0,
    explanation: "Overfitting xảy ra khi mô hình học cả nhiễu và ghi nhớ dữ liệu train.",
  },
  {
    id: 47,
    topic: "Đánh giá mô hình",
    question: "Underfitting thường xảy ra khi mô hình như thế nào?",
    options: ["Quá đơn giản để học quy luật", "Quá khớp dữ liệu train", "Có quá nhiều màu", "Được lưu đúng định dạng"],
    answer: 0,
    explanation: "Mô hình quá đơn giản thường có sai số cao ngay cả trên tập train.",
  },
  {
    id: 48,
    topic: "Đánh giá mô hình",
    question: "Cross-validation giúp làm gì?",
    options: ["Đánh giá mô hình trên nhiều cách chia dữ liệu", "Tăng độ phân giải ảnh", "Đổi hệ điều hành", "Tạo mật khẩu"],
    answer: 0,
    explanation: "Cross-validation cho ước lượng ổn định hơn bằng cách luân phiên các phần dữ liệu.",
  },
  {
    id: 49,
    topic: "Đánh giá mô hình",
    question: "Hyperparameter là gì?",
    options: ["Giá trị cấu hình đặt trước khi huấn luyện", "Nhãn thật của dữ liệu", "Một hàng bị thiếu", "Kết quả dự đoán"],
    answer: 0,
    explanation: "Ví dụ hyperparameter: k của KNN, max_depth của cây quyết định.",
  },
  {
    id: 50,
    topic: "Đánh giá mô hình",
    question: "Grid Search thường dùng để làm gì?",
    options: ["Tìm tổ hợp hyperparameter phù hợp", "Tạo bảng tính", "Xóa dữ liệu test", "Đổi tên thư viện"],
    answer: 0,
    explanation: "Grid Search thử một lưới cấu hình và chọn cấu hình có kết quả tốt.",
  },
  {
    id: 51,
    topic: "Thuật toán",
    question: "KNN dự đoán dựa trên điều gì?",
    options: ["Các láng giềng gần nhất", "Thứ tự tên tệp", "Màu nền", "Dung lượng ổ cứng"],
    answer: 0,
    explanation: "K-Nearest Neighbors xem xét nhãn hoặc giá trị của các điểm gần nhất.",
  },
  {
    id: 52,
    topic: "Thuật toán",
    question: "Trong KNN, K biểu diễn điều gì?",
    options: ["Số láng giềng được xét", "Số cột target", "Số lần lưu tệp", "Số lớp luôn phải có"],
    answer: 0,
    explanation: "K là số điểm lân cận tham gia bỏ phiếu hoặc tính trung bình.",
  },
  {
    id: 53,
    topic: "Thuật toán",
    question: "KNN nhạy với vấn đề nào của dữ liệu?",
    options: ["Khác biệt thang đo giữa các feature", "Tên DataFrame", "Màu chữ", "Đuôi tệp Python"],
    answer: 0,
    explanation: "KNN dùng khoảng cách nên thường cần chuẩn hóa feature.",
  },
  {
    id: 54,
    topic: "Thuật toán",
    question: "Decision Tree đưa ra quyết định bằng cách nào?",
    options: ["Chia dữ liệu qua các điều kiện", "Chỉ tính trung bình", "Chỉ xáo trộn nhãn", "Không dùng feature"],
    answer: 0,
    explanation: "Cây quyết định liên tiếp kiểm tra các điều kiện trên feature.",
  },
  {
    id: 55,
    topic: "Thuật toán",
    question: "Nút cuối của Decision Tree thường được gọi là gì?",
    options: ["Leaf", "Root file", "Epoch", "Kernel"],
    answer: 0,
    explanation: "Leaf node chứa dự đoán cuối cùng của cây.",
  },
  {
    id: 56,
    topic: "Thuật toán",
    question: "max_depth trong Decision Tree kiểm soát điều gì?",
    options: ["Độ sâu tối đa của cây", "Số cột dữ liệu", "Tốc độ mạng", "Kích thước màn hình"],
    answer: 0,
    explanation: "Giới hạn độ sâu giúp kiểm soát độ phức tạp và giảm overfitting.",
  },
  {
    id: 57,
    topic: "Thuật toán",
    question: "Random Forest gồm nhiều mô hình cơ sở nào?",
    options: ["Decision Tree", "Linear Regression duy nhất", "K-Means duy nhất", "PCA"],
    answer: 0,
    explanation: "Random Forest kết hợp dự đoán của nhiều cây quyết định.",
  },
  {
    id: 58,
    topic: "Thuật toán",
    question: "Ý tưởng chính của ensemble learning là gì?",
    options: ["Kết hợp nhiều mô hình", "Chỉ dùng một mẫu", "Xóa toàn bộ feature", "Không đánh giá mô hình"],
    answer: 0,
    explanation: "Ensemble tận dụng nhiều mô hình để tạo kết quả ổn định hoặc chính xác hơn.",
  },
  {
    id: 59,
    topic: "Thuật toán",
    question: "Bagging chủ yếu huấn luyện các mô hình như thế nào?",
    options: ["Song song trên các mẫu dữ liệu khác nhau", "Chỉ trên một hàng", "Không cần dữ liệu", "Chỉ theo thứ tự bảng chữ cái"],
    answer: 0,
    explanation: "Bagging dùng các mẫu bootstrap và thường kết hợp mô hình theo kiểu song song.",
  },
  {
    id: 60,
    topic: "Thuật toán",
    question: "Boosting xây dựng các mô hình mới để làm gì?",
    options: ["Sửa dần lỗi của các mô hình trước", "Xóa target", "Tăng số màn hình", "Đổi ngôn ngữ lập trình"],
    answer: 0,
    explanation: "Boosting tập trung dần vào các mẫu hoặc phần sai số khó.",
  },
  {
    id: 61,
    topic: "Thuật toán",
    question: "Naive Bayes dựa trên định lý nào?",
    options: ["Bayes", "Pythagoras", "Ohm", "Newton về chuyển động"],
    answer: 0,
    explanation: "Naive Bayes sử dụng định lý Bayes với giả định độc lập có điều kiện đơn giản hóa.",
  },
  {
    id: 62,
    topic: "Thuật toán",
    question: "Naive Bayes thường hoạt động tốt trong ví dụ nào?",
    options: ["Phân loại văn bản", "Tăng độ phân giải màn hình", "Nén thư mục", "Quản lý pin"],
    answer: 0,
    explanation: "Naive Bayes là baseline phổ biến cho spam và phân loại tài liệu.",
  },
  {
    id: 63,
    topic: "Thuật toán",
    question: "Mục tiêu của SVM là tìm gì?",
    options: ["Siêu phẳng phân tách với biên lớn", "Trung bình của mọi target", "Tên cột dài nhất", "Tệp nhỏ nhất"],
    answer: 0,
    explanation: "SVM tìm ranh giới có margin lớn giữa các lớp.",
  },
  {
    id: 64,
    topic: "Thuật toán",
    question: "Kernel trong SVM giúp xử lý điều gì?",
    options: ["Quan hệ phi tuyến", "Tệp âm thanh", "Màu giao diện", "Số trang in"],
    answer: 0,
    explanation: "Kernel ánh xạ dữ liệu để tạo ranh giới phi tuyến hiệu quả.",
  },
  {
    id: 65,
    topic: "Thuật toán",
    question: "Scikit-learn là gì?",
    options: ["Thư viện Machine Learning cho Python", "Hệ điều hành", "Trình duyệt", "Cơ sở dữ liệu"],
    answer: 0,
    explanation: "Scikit-learn cung cấp thuật toán, tiền xử lý và công cụ đánh giá ML.",
  },
  {
    id: 66,
    topic: "Học không giám sát",
    question: "Học không giám sát thường làm việc với dữ liệu như thế nào?",
    options: ["Không có nhãn mục tiêu sẵn", "Luôn có đúng hai nhãn", "Không có feature", "Chỉ có một hàng"],
    answer: 0,
    explanation: "Unsupervised learning tìm cấu trúc ẩn khi không có label.",
  },
  {
    id: 67,
    topic: "Học không giám sát",
    question: "K-Means là thuật toán dùng cho việc gì?",
    options: ["Phân cụm", "Hồi quy tuyến tính", "Nén văn bản", "Tạo mật khẩu"],
    answer: 0,
    explanation: "K-Means chia các điểm dữ liệu thành K cụm.",
  },
  {
    id: 68,
    topic: "Học không giám sát",
    question: "Trong K-Means, K là gì?",
    options: ["Số cụm mong muốn", "Số nhãn đã biết", "Số feature bắt buộc", "Số lần mở tệp"],
    answer: 0,
    explanation: "Người dùng chọn K là số tâm cụm và số nhóm cần tìm.",
  },
  {
    id: 69,
    topic: "Học không giám sát",
    question: "Centroid trong K-Means là gì?",
    options: ["Tâm đại diện của một cụm", "Một nhãn thật", "Một tệp cấu hình", "Một siêu phẳng SVM"],
    answer: 0,
    explanation: "Centroid thường là trung bình tọa độ các điểm trong cụm.",
  },
  {
    id: 70,
    topic: "Học không giám sát",
    question: "K-Means thường gán mỗi điểm vào cụm dựa trên yếu tố nào?",
    options: ["Centroid gần nhất", "Tên điểm dài nhất", "Thứ tự nhập", "Màu bất kỳ"],
    answer: 0,
    explanation: "Mỗi điểm được gán cho tâm cụm có khoảng cách nhỏ nhất.",
  },
  {
    id: 71,
    topic: "Học không giám sát",
    question: "PCA thường được dùng để làm gì?",
    options: ["Giảm chiều dữ liệu", "Tạo nhãn thủ công", "Tăng số hàng bắt buộc", "Mã hóa mật khẩu"],
    answer: 0,
    explanation: "PCA tạo các thành phần chính giữ nhiều phương sai với ít chiều hơn.",
  },
  {
    id: 72,
    topic: "Học không giám sát",
    question: "Các thành phần chính trong PCA có quan hệ thế nào?",
    options: ["Trực giao với nhau", "Luôn giống nhau", "Luôn bằng target", "Không dùng dữ liệu"],
    answer: 0,
    explanation: "Các principal components trực giao, nên không tương quan tuyến tính với nhau.",
  },
  {
    id: 73,
    topic: "Học không giám sát",
    question: "Silhouette Score thường đánh giá điều gì?",
    options: ["Chất lượng phân cụm", "Độ chính xác hồi quy", "Dung lượng tệp", "Tốc độ mạng"],
    answer: 0,
    explanation: "Silhouette đo mức điểm gần cụm của mình và xa các cụm khác.",
  },
  {
    id: 74,
    topic: "Học không giám sát",
    question: "Phân khúc khách hàng khi chưa có nhãn sẵn là ví dụ của gì?",
    options: ["Clustering", "Regression", "Binary classification", "Data leakage"],
    answer: 0,
    explanation: "Clustering có thể khám phá các nhóm khách hàng có đặc điểm tương tự.",
  },
  {
    id: 75,
    topic: "Mạng nơ-ron",
    question: "Đơn vị cơ bản của mạng nơ-ron nhân tạo thường được gọi là gì?",
    options: ["Neuron", "Cluster", "DataFrame", "Folder"],
    answer: 0,
    explanation: "Mạng nơ-ron được cấu thành từ các neuron hoặc node liên kết.",
  },
  {
    id: 76,
    topic: "Mạng nơ-ron",
    question: "Lớp nhận dữ liệu ban đầu của mạng nơ-ron là lớp nào?",
    options: ["Input layer", "Output layer", "Hidden file", "Cluster layer"],
    answer: 0,
    explanation: "Input layer nhận vector đặc trưng đầu vào.",
  },
  {
    id: 77,
    topic: "Mạng nơ-ron",
    question: "Hidden layer nằm ở đâu?",
    options: ["Giữa input và output", "Sau khi lưu tệp", "Ngoài mô hình", "Trong trình duyệt"],
    answer: 0,
    explanation: "Các hidden layer thực hiện biến đổi trung gian giữa đầu vào và đầu ra.",
  },
  {
    id: 78,
    topic: "Mạng nơ-ron",
    question: "Activation function giúp mạng nơ-ron học điều gì?",
    options: ["Quan hệ phi tuyến", "Chỉ phép cộng tuyến tính", "Tên tệp", "Độ sáng màn hình"],
    answer: 0,
    explanation: "Hàm kích hoạt phi tuyến giúp mạng biểu diễn các quan hệ phức tạp.",
  },
  {
    id: 79,
    topic: "Mạng nơ-ron",
    question: "ReLU trả về giá trị nào khi đầu vào âm?",
    options: ["0", "1", "Chính đầu vào âm", "Luôn là 100"],
    answer: 0,
    explanation: "ReLU(x) = max(0, x), vì vậy đầu vào âm cho kết quả 0.",
  },
  {
    id: 80,
    topic: "Mạng nơ-ron",
    question: "Một epoch là gì?",
    options: ["Một lượt mô hình đi qua toàn bộ tập training", "Một feature", "Một nhãn", "Một thư viện"],
    answer: 0,
    explanation: "Một epoch hoàn thành khi toàn bộ dữ liệu training đã được xử lý một lượt.",
  },
  {
    id: 81,
    topic: "Mạng nơ-ron",
    question: "Batch size là gì?",
    options: ["Số mẫu xử lý trước mỗi lần cập nhật", "Số lớp đầu ra bắt buộc", "Số cột bị xóa", "Số mô hình trong KNN"],
    answer: 0,
    explanation: "Batch size quyết định số mẫu dùng để tính gradient cho mỗi bước cập nhật.",
  },
  {
    id: 82,
    topic: "Mạng nơ-ron",
    question: "Learning rate kiểm soát điều gì?",
    options: ["Kích thước bước cập nhật tham số", "Số cột dữ liệu", "Số nhãn thật", "Kích thước ảnh"],
    answer: 0,
    explanation: "Learning rate quyết định mỗi bước tối ưu thay đổi trọng số nhiều hay ít.",
  },
  {
    id: 83,
    topic: "Mạng nơ-ron",
    question: "Backpropagation dùng để làm gì?",
    options: ["Tính gradient để cập nhật trọng số", "Chia dữ liệu thành cụm", "Đổi tên target", "Tạo DataFrame"],
    answer: 0,
    explanation: "Backpropagation truyền lỗi ngược qua mạng để tính gradient.",
  },
  {
    id: 84,
    topic: "Mạng nơ-ron",
    question: "CNN đặc biệt phù hợp với loại dữ liệu nào?",
    options: ["Hình ảnh", "Chỉ bảng hai cột", "Chỉ địa chỉ web", "Chỉ mật khẩu"],
    answer: 0,
    explanation: "Convolutional Neural Network khai thác tốt cấu trúc không gian của ảnh.",
  },
  {
    id: 85,
    topic: "Python cho ML",
    question: "NumPy nổi tiếng với cấu trúc dữ liệu nào?",
    options: ["Mảng nhiều chiều", "Trang HTML", "Hộp thư", "Tệp trình chiếu"],
    answer: 0,
    explanation: "ndarray của NumPy hỗ trợ tính toán số hiệu quả trên mảng nhiều chiều.",
  },
  {
    id: 86,
    topic: "Python cho ML",
    question: "Cấu trúc bảng hai chiều chính trong Pandas là gì?",
    options: ["DataFrame", "Neuron", "Kernel", "Epoch"],
    answer: 0,
    explanation: "DataFrame lưu dữ liệu dạng hàng và cột có nhãn.",
  },
  {
    id: 87,
    topic: "Python cho ML",
    question: "Hàm train_test_split thuộc mục đích nào?",
    options: ["Chia dữ liệu train và test", "Vẽ cây", "Tạo cluster", "Tải ảnh"],
    answer: 0,
    explanation: "train_test_split là tiện ích phổ biến của scikit-learn để chia tập dữ liệu.",
  },
  {
    id: 88,
    topic: "Python cho ML",
    question: "Phương thức fit() của mô hình scikit-learn thường làm gì?",
    options: ["Huấn luyện mô hình", "Xóa mô hình", "Đóng Python", "In dữ liệu"],
    answer: 0,
    explanation: "fit() học các tham số của mô hình từ dữ liệu training.",
  },
  {
    id: 89,
    topic: "Python cho ML",
    question: "Phương thức predict() thường nhận dữ liệu nào?",
    options: ["Feature của các mẫu cần dự đoán", "Chỉ target thật", "Tên tệp", "Siêu tham số duy nhất"],
    answer: 0,
    explanation: "predict() dùng các feature đầu vào để trả về nhãn hoặc giá trị dự đoán.",
  },
  {
    id: 90,
    topic: "Python cho ML",
    question: "random_state giúp điều gì khi chia dữ liệu?",
    options: ["Tái lập cùng kết quả ngẫu nhiên", "Tăng số feature", "Xóa outlier", "Tự tạo target"],
    answer: 0,
    explanation: "Cố định random_state giúp các lần chạy tạo cùng cách chia hoặc cùng ngẫu nhiên.",
  },
];
